Previously an unintentional change introduced by a PR caused the post_testcase function to not run if an Exception
occurred. This functionality has been restored.